language: ruby

bundler_args: --without development production

rvm:
  - 2.1.0

after_script:
  - gem install heroku
  - export HEROKU_API_KEY=ER/0jtJUjLieq0tOEMW3nLQruFqWhLyGL1QqrTnoj0AAkRrbsyMiBYIPeqG3fZJbkqQh+enJrFUayFa1/KQa5t9ayODH+eIRTkuk7OcVfuAZmWUctyrgHppHb9Z7OidIoHNKwMpIqjjThRydry/+5WLaRsI6fCFDg8G6y8n43wg=
  - yes | ruby travis_deployer.rb
  - heroku keys:clear
  - yes | heroku keys:add
  - git push heroku master # or whatever your heroku push looks like

notifications:
  email:
    - paul@paulcarvill.com