language: ruby

bundler_args: --without development production

rvm:
  - 2.0.0

before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc' # skip installing docs for gems

before_script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate

script:
  - RAILS_ENV=test bundle exec rake

deploy:
  provider: heroku
  api_key:
    secure: GDApQ045u6gIzaBckvvbOa1nJ5DDzpHLPcEkeiJ46Zd9RpCdZLQYy3j+7FSGNRQF6cgzKrvsxysyDR9Tnp76xl1B+AJLpArSCiIDmSf2xOZ2/RlFXKX9SdMA6VENiaE7YlPEfOaQaq2Bpofz5sAyBc43MQnVdrDEtcLkSflhj3o=
  app: goodtunes-staging
  on:
    repo: CheeseShed/GoodTunes
  run: "rake db:drop db:migrate db:seed"

notifications:
  email:
    - paul@paulcarvill.com
    - jamie.newman@gmail.com
    - ihuntington85@gmail.com