language: ruby

bundler_args: --without development production

rvm:
  - 2.1.0

env:
  global:
    - secure: GDApQ045u6gIzaBckvvbOa1nJ5DDzpHLPcEkeiJ46Zd9RpCdZLQYy3j+7FSGNRQF6cgzKrvsxysyDR9Tnp76xl1B+AJLpArSCiIDmSf2xOZ2/RlFXKX9SdMA6VENiaE7YlPEfOaQaq2Bpofz5sAyBc43MQnVdrDEtcLkSflhj3o=

after_success:
    - gem install heroku
    - git remote add heroku git@heroku.com:goodtunes-staging.git
    - echo "Host heroku.com" >> ~/.ssh/config
    - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
    - echo "   CheckHostIP no" >> ~/.ssh/config
    - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
    - heroku keys:clear
    - yes | heroku keys:add


notifications:
  email:
    - paul@paulcarvill.com